--Which are the top 10 apps having the highest rating in the given available dataset
select App,rating
from cleaned_apps_db
order by rating desc
limit 10

--What is the number of installs and reviews for the top 5 most reviewed apps?
select App,Installs, Reviews 
from cleaned_apps_db
order by Reviews desc
limit 5

--Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
select App, Reviews, Category
from cleaned_apps_db
order by reviews desc
limit 1

--What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
select sum(Installs * price)
from cleaned_apps_db

--Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
select Category, sum(installs) as s
from cleaned_apps_db
group by Category
order by s desc
limit 1

--Which Genre has the most number of published apps?
select genres , count(*) as c
from cleaned_apps_db
group by genres
order by c desc
limit 1

--Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
select distinct(App), Installs
from cleaned_apps_db
where Category = 'GAME'
order by Installs desc

--How many apps from the given data set are free? Also, provide the number of paid apps.
select Type, count(*)
from cleaned_apps_db
group by Type

--Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
select App,Reviews
from cleaned_apps_db
where Category='DATING'
order by Reviews desc
limit 1

--Get the number of reviews having positive sentiment and the number of reviews having negative sentiment for the app 10 best foods for You and compare them.
select Sentiment,count(*) from cleaned_reviews_db
where app='10 Best Foods for You'
group by Sentiment
having Sentiment != 'Neutral'

--Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
select App, Translated_Review, Sentiment_Polarity, Sentiment_Subjectivity 
from cleaned_reviews_db
where App='ASUS SuperNote' and Sentiment_Polarity=1 and Sentiment_Subjectivity=1

--Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat
select * from cleaned_reviews_db
where app='Abs Training-Burn belly fat'
and sentiment='Neutral'

--Extract all negative sentiment reviews for ASUS Supernote with their sentiment polarity and sentiment subjectivity
select Translated_Review, Sentiment_Polarity, Sentiment_Subjectivity from cleaned_reviews_db
where app='Asus Supernote'
and sentiment='Negative'
